var annotated_dup =
[
    [ "fmt", null, [
      [ "formatter< String >", "structfmt_1_1formatter_3_01_string_01_4.html", "structfmt_1_1formatter_3_01_string_01_4" ]
    ] ],
    [ "Allocator", "class_allocator.html", "class_allocator" ],
    [ "ArgumentCommandNode", "class_argument_command_node.html", "class_argument_command_node" ],
    [ "Array", "class_array.html", "class_array" ],
    [ "AttachmentProperties", "struct_attachment_properties.html", "struct_attachment_properties" ],
    [ "BasicLightComponent", "class_basic_light_component.html", "class_basic_light_component" ],
    [ "CameraComponent", "class_camera_component.html", "class_camera_component" ],
    [ "CameraManager", "class_camera_manager.html", "class_camera_manager" ],
    [ "Color", "struct_color.html", "struct_color" ],
    [ "CommandContext", "class_command_context.html", "class_command_context" ],
    [ "CommandNode", "class_command_node.html", "class_command_node" ],
    [ "CommandTree", "class_command_tree.html", "class_command_tree" ],
    [ "Console", "class_console.html", "class_console" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "Entry", "class_entry.html", "class_entry" ],
    [ "Exception", "class_exception.html", "class_exception" ],
    [ "ExecutableCommandNode", "class_executable_command_node.html", "class_executable_command_node" ],
    [ "IEName", "class_i_e_name.html", "class_i_e_name" ],
    [ "InputManager", "class_input_manager.html", "class_input_manager" ],
    [ "KeyBind", "struct_key_bind.html", "struct_key_bind" ],
    [ "LinearColor", "struct_linear_color.html", "struct_linear_color" ],
    [ "LinearColors", "struct_linear_colors.html", "struct_linear_colors" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "Material", "struct_material.html", "struct_material" ],
    [ "Math", "class_math.html", "class_math" ],
    [ "Matrix3", "struct_matrix3.html", "struct_matrix3" ],
    [ "Matrix4", "struct_matrix4.html", "struct_matrix4" ],
    [ "Memory", "class_memory.html", "class_memory" ],
    [ "Mesh", "struct_mesh.html", "struct_mesh" ],
    [ "MeshComponent", "class_mesh_component.html", "class_mesh_component" ],
    [ "Model", "struct_model.html", "struct_model" ],
    [ "Object", "class_object.html", "class_object" ],
    [ "Optional", "class_optional.html", "class_optional" ],
    [ "PerformanceWindow", "class_performance_window.html", "class_performance_window" ],
    [ "PlatformData", "struct_platform_data.html", "struct_platform_data" ],
    [ "Random", "class_random.html", "class_random" ],
    [ "RefCounter", "class_ref_counter.html", "class_ref_counter" ],
    [ "Renderable", "class_renderable.html", "class_renderable" ],
    [ "ResourceLoader", "class_resource_loader.html", "class_resource_loader" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "SceneComponent", "class_scene_component.html", "class_scene_component" ],
    [ "SceneObject", "class_scene_object.html", "class_scene_object" ],
    [ "ShaderManager", "class_shader_manager.html", "class_shader_manager" ],
    [ "ShaderPrograms", "class_shader_programs.html", "class_shader_programs" ],
    [ "SharedPointer", "class_shared_pointer.html", "class_shared_pointer" ],
    [ "StackFrame", "struct_stack_frame.html", "struct_stack_frame" ],
    [ "StackTrace", "class_stack_trace.html", "class_stack_trace" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ],
    [ "String", "class_string.html", "class_string" ],
    [ "Texture", "struct_texture.html", "struct_texture" ],
    [ "Transform", "struct_transform.html", "struct_transform" ],
    [ "Uniforms", "class_uniforms.html", "class_uniforms" ],
    [ "UniquePointer", "class_unique_pointer.html", "class_unique_pointer" ],
    [ "Vector2", "struct_vector2.html", "struct_vector2" ],
    [ "Vector3", "struct_vector3.html", "struct_vector3" ],
    [ "Vector4", "struct_vector4.html", "struct_vector4" ],
    [ "Vertex", "struct_vertex.html", "struct_vertex" ],
    [ "WeakPointer", "class_weak_pointer.html", "class_weak_pointer" ]
];