var annotated_dup =
[
    [ "fmt", null, [
      [ "formatter< String >", "structfmt_1_1formatter_3_01_string_01_4.html", "structfmt_1_1formatter_3_01_string_01_4" ]
    ] ],
    [ "Allocator", "class_allocator.html", "class_allocator" ],
    [ "Array", "class_array.html", "class_array" ],
    [ "Attenuation", "struct_attenuation.html", "struct_attenuation" ],
    [ "AutoReleaseArray", "struct_auto_release_array.html", "struct_auto_release_array" ],
    [ "CameraComponent", "class_camera_component.html", "class_camera_component" ],
    [ "CameraManager", "class_camera_manager.html", "class_camera_manager" ],
    [ "CharacterInfoWindow", "class_character_info_window.html", "class_character_info_window" ],
    [ "DirectionalLight", "struct_directional_light.html", "struct_directional_light" ],
    [ "DirectionalLightHandles", "struct_directional_light_handles.html", "struct_directional_light_handles" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "Entry", "class_entry.html", "class_entry" ],
    [ "FlyingCharacter", "class_flying_character.html", "class_flying_character" ],
    [ "IEName", "class_i_e_name.html", "class_i_e_name" ],
    [ "InputManager", "class_input_manager.html", "class_input_manager" ],
    [ "IRenderable", "class_i_renderable.html", "class_i_renderable" ],
    [ "KeyBind", "struct_key_bind.html", "struct_key_bind" ],
    [ "LinearColor", "struct_linear_color.html", "struct_linear_color" ],
    [ "LinearColors", "struct_linear_colors.html", "struct_linear_colors" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "Material", "struct_material.html", "struct_material" ],
    [ "MaterialHandles", "struct_material_handles.html", "struct_material_handles" ],
    [ "Math", "class_math.html", "class_math" ],
    [ "Matrix3", "struct_matrix3.html", "struct_matrix3" ],
    [ "Matrix4", "struct_matrix4.html", "struct_matrix4" ],
    [ "Memory", "class_memory.html", "class_memory" ],
    [ "Mesh", "struct_mesh.html", "struct_mesh" ],
    [ "MeshComponent", "class_mesh_component.html", "class_mesh_component" ],
    [ "MeshObject", "class_mesh_object.html", "class_mesh_object" ],
    [ "Object", "class_object.html", "class_object" ],
    [ "Optional", "class_optional.html", "class_optional" ],
    [ "PerformanceWindow", "class_performance_window.html", "class_performance_window" ],
    [ "PlatformData", "struct_platform_data.html", "struct_platform_data" ],
    [ "PointLight", "struct_point_light.html", "struct_point_light" ],
    [ "PointLightHandles", "struct_point_light_handles.html", "struct_point_light_handles" ],
    [ "Random", "class_random.html", "class_random" ],
    [ "ResourceLoader", "class_resource_loader.html", "class_resource_loader" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "SceneComponent", "class_scene_component.html", "class_scene_component" ],
    [ "SceneObject", "class_scene_object.html", "class_scene_object" ],
    [ "String", "class_string.html", "class_string" ],
    [ "Transform", "struct_transform.html", "struct_transform" ],
    [ "Vector2", "struct_vector2.html", "struct_vector2" ],
    [ "Vector3", "struct_vector3.html", "struct_vector3" ],
    [ "Vector4", "struct_vector4.html", "struct_vector4" ],
    [ "Vertex", "struct_vertex.html", "struct_vertex" ]
];